{% set version = "0.3.1" %}

package:
  name: fast-query-parsers
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/fast-query-parsers/fast_query_parsers-{{ version }}.tar.gz
  sha256: f8878fffe0249159a8deaaeb0095c3a2af202921e97b2c56d0dbdf4c39032672
  patches:
    # TODO remove after https://github.com/starlite-api/fast-query-parsers/pull/16
    - 0000-no-runtime-maturin.patch

build:
  skip: True  # [py<38]
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - maturin >=0.13,<0.14
    - pip
    - python
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - fast_query_parsers
  commands:
    - pip check
    - pytest -vv --cov=fast_query_parsers --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=83
    - mypy -p fast_query_parsers
  requires:
    - mypy
    - pip
    - pytest-cov

about:
  home: https://github.com/starlite-api/fast-query-parsers
  summary: Ultra-fast query string and url-encoded form-data parsers
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - bollwyvl
